apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: ping-cert
spec:
  dnsNames:
    - ping.nnazo.dev
  secretName: ping-cert
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
